using 'main.bicep'

param sites_tigergrades_name = 'tigergrades'
param components_tigergrades_name = 'tigergrades'
param namespaces_tiger_grades_bus_name = 'tiger-grades-bus'
param serverfarms_ASP_tigergradesgroup_98ad_name = 'ASP-tigergradesgroup-98ad'
param storageAccounts_tigergradesgroup9e7b_name = 'tigergradesgroup9e7b'
param storageAccounts_tigergradesgroupaa96_name = 'tigergradesgroupaa96'
param schedulers_tiger_grades_scheduler_name = 'tiger-grades-scheduler'
param actionGroups_Application_Insights_Smart_Detection_name = 'Application Insights Smart Detection'
param userAssignedIdentities_tigergrades_id_8bcc_name = 'tigergrades-id-8bcc'
param workspaces_DefaultWorkspace_6c17570e_c7c0_49d1_a38d_ae287afc2f84_EA_externalid = '/subscriptions/6c17570e-c7c0-49d1-a38d-ae287afc2f84/resourceGroups/DefaultResourceGroup-EA/providers/Microsoft.OperationalInsights/workspaces/DefaultWorkspace-6c17570e-c7c0-49d1-a38d-ae287afc2f84-EA' 
